### PR TITLE
Fix namespace rename

### LINKED ISSUE #1121: Renaming a namespace results in the wrong name
**Describe the bug**
Request to rename `my.app.ui.foo` to `my.app.ui.reachability.foo`. This creates a new file named `my/app/ui/reachability/foo.clj` (correct) but sets the namespace to `my.app.ui.reachability.foochability.foo` (incorrect).

**Expected behavior**
The namespace should be `my.app.ui.reachability.foo`.

**Logs**
<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
[Trace - 11:43:29 AM] Sending request 'textDocument/prepareRename - (16327)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/cljs/my/app/ui/foo.cljs"
  },
  "position": {
    "line": 0,
    "character": 14
  }
}

[Trace - 11:43:29 AM] Received response 'textDocument/prepareRename - (16327)' in 13ms.
Result: {
  "start": {
    "line": 0,
    "character": 4
  },
  "end": {
    "line": 0,
    "character": 17
  }
}

[Trace - 11:43:41 AM] Sending request 'textDocument/rename - (16328)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/cljs/my/app/ui/foo.cljs"
  },
  "position": {
    "line": 0,
    "character": 14
  },
  "newName": "my.app.ui.reachability.foo"
}

[Trace - 11:43:41 AM] Received response 'textDocument/rename - (16328)' in 23ms.
Result: {
  "documentChanges": [
    {
      "textDocument": {
        "version": 128,
        "uri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/cljs/my/app/ui/foo.cljs"
      },
      "edits": [
        {
          "range": {
            "start": {
              "line": 0,
              "character": 4
            },
            "end": {
              "line": 0,
              "character": 17
            }
          },
          "newText": "my.app.ui.reachability.foo"
        }
      ]
    },
    {
      "oldUri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/cljs/my/app/ui/foo.cljs",
      "newUri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/clj/my/app/ui/reachability/foo.cljs",
      "kind": "rename"
    }
  ]
}

[Trace - 11:43:41 AM] Sending notification 'textDocument/didSave'.
Params: {
  "textDocument": {
    "uri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/cljs/my/app/ui/foo.cljs",
    "version": 130
  },
  "text": "(ns my.app.ui.reachability.foo)\n"
}

[Trace - 11:43:41 AM] Sending notification 'textDocument/didChange'.
Params: {
  "textDocument": {
    "uri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/cljs/my/app/ui/foo.cljs",
    "version": 130
  },
  "contentChanges": [
    {
      "text": "(ns my.app.ui.reachability.foo)\n"
    }
  ]
}

[Trace - 11:43:41 AM] Sending notification 'textDocument/didClose'.
Params: {
  "textDocument": {
    "uri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/cljs/my/app/ui/foo.cljs"
  }
}

[Trace - 11:43:41 AM] Sending request 'workspace/willRenameFiles - (16329)'.
Params: {
  "files": [
    {
      "oldUri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/cljs/my/app/ui/foo.cljs",
      "newUri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/clj/my/app/ui/reachability/foo.cljs"
    }
  ]
}

[Trace - 11:43:41 AM] Received response 'workspace/willRenameFiles - (16329)' in 12ms.
Result: {
  "documentChanges": [
    {
      "textDocument": {
        "version": 130,
        "uri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/cljs/my/app/ui/foo.cljs"
      },
      "edits": [
        {
          "range": {
            "start": {
              "line": 0,
              "character": 4
            },
            "end": {
              "line": 0,
              "character": 17
            }
          },
          "newText": "my.app.ui.reachability.foo"
        }
      ]
    }
  ]
}

[Trace - 11:43:41 AM] Sending notification 'textDocument/didClose'.
Params: {
  "textDocument": {
    "uri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/clj/my/app/ui/reachability/foo.cljs"
  }
}

[Trace - 11:43:41 AM] Sending notification 'textDocument/didChange'.
Params: {
  "textDocument": {
    "uri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/cljs/my/app/ui/foo.cljs",
    "version": 131
  },
  "contentChanges": [
    {
      "text": "(ns my.app.ui.reachability.foochability.foo)\n"
    }
  ]
}

[Trace - 11:43:41 AM] Sending request 'textDocument/semanticTokens/range - (16330)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/clj/my/app/ui/reachability/foo.cljs"
  },
  "range": {
    "start": {
      "line": 0,
      "character": 0
    },
    "end": {
      "line": 1,
      "character": 0
    }
  }
}

[Trace - 11:43:41 AM] Sending notification 'textDocument/didOpen'.
Params: {
  "textDocument": {
    "uri": "file:///Users/jmaine/workspace/opensource/lsp-rename-repro/src/clj/my/app/ui/reachability/foo.cljs",
    "languageId": "clojurescript",
    "version": 131,
    "text": "(ns my.app.ui.reachability.foochability.foo)\n"
  }
}

</pre>
</details>

**User details (please complete the following information):**
 - Editor Emacs

**Analysis**

I can see why this is happening, or at least partially. You can follow along in the logs above. It's an interaction between `textDocument/rename` and `workspace/willRenameFiles`.

In Emacs (other editors may follow a different sequence), first the client and server communicate to prepare for a rename.

Then, the client sends a `textDocument/rename` request, saying "I'm on the 14th character of the first line of 'my/app/ui/foo.cljs'. I want to rename the thing there to `my.app.ui.reachability.foo`."

The server responds by saying "OK, on the first line, replace chars 4-17 with `my.app.ui.reachability.foo`. Also rename the file 'my/app/ui/foo.cljs' to 'my/app/ui/reachability/foo.cljs'."

The client starts executing these commands. First it edits the old file to contain the new ns. It notifies the server of that change (twice, once with `textDocument/didSave` and once with `textDocument/didChange`). Then it starts the file rename. First it closes the old file. Then it sends the server a `workspace/willRenameFiles` request, saying that it is about to rename the old file to the new file.

And here's where the buggy text is introduced... The server responds by telling the client "on the first line of the old file, replace chars 4-17 with `my.app.ui.reachability.foo`". But this is wrong. The server seems to think that characters 4-17 are `my.app.ui.foo`, when they are actually `my.app.ui.rea` (followed by `chability.foo`). Effectively, the server is telling the client to apply the same edit for a second time. When the client follows the server's directions, it edits the old file. After replacing characters 4-17, the namespace ends up being `my.app.ui.reachability.foochability.foo`.

To finish off the sequence, the client tells the server about the change to the old file, including the buggy text. Then it renames the file on the filesystem (I presume; the logs don't actually say when the client does this). Then it opens the new file, and notifies the server, again including the buggy text.

So, the question is, why? During `workspace/willRenameFiles`, the server has looked in the analysis for the namespace of the old file and found `my.app.ui.foo`. That's why it think characters 4-17 should be replaced. Though the client told the server that the old file contains the new ns via `textDocument/didChange`, the server is still analyzing that change asynchronously when it receives `workspace/willRenameFiles`.

@ericdallo you rolled back the `swap!` which fixed it... I haven't watched the logs to analyze why, but I have a guess. That swap moves the analysis of 'my/app/ui/foo.cljs' to 'my/app/ui/reachability/foo.cljs' during the first request, `textDocument/rename`. Then in the second request `workspace/willRenameFiles` we have no analysis for 'my/app/ui/foo.cljs', and so the server doesn't generate any edits. This works, but not for the right reasons. That swap is definitely wrong, so it needs to be removed.

So what's a better fix? We should probably wait for analysis to finish before handling `workspace/willRenameFiles`. But maybe there's a better fix. In the first request `textDocument/rename`, instead of responding with both the text edits and the file rename, we could respond with just the file rename. Then we can rely on `workspace/willRenameFiles` to apply the edit. Or maybe not... I'm not sure all clients have will-rename capabilities. I'll think about it more.

### PR DESCRIPTION
**Pull request by mainej**
This fixes #1121. It also restores #1049, which was temporarily reverted as a quick fox for #1121.

When a user asks to rename a namespace, we instruct the client to edit the namespace and to rename the file. The client makes the edit (in the old file), then tell us via didChange. We start an asynchronous analysis. Then, the client sends us willRenameFiles. We respond by (incorrectly) asking the client to make the same edit to the old file we asked for before. The reason we do this is we haven't waited for the analysis to finish, so we think the file still has its old namespace.

This changes will-rename-files to wait for the analysis to finish. It also changes it to return no edits if the namespace has already been edited (which it has in this scenario, though it wouldn't if the file had been renamed because of something besides a rename refactoring).

Finally, it fixes another bug where we weren't clearing the diagnostics of deleted files. In my Emacs, rename refactorings still cause erroneous lint (we ask clj-kondo to analyze #.foo.clj, which doesn't exist, and it complains about that) but that might just be because of my Emacs config.

- [x] I created an issue to discuss the problem I am trying to solve or an open issue already exists.
- [x] I added a new entry to [CHANGELOG.md](https://github.com/clojure-lsp/clojure-lsp/blob/master/CHANGELOG.md)
- ~I updated documentation if applicable (`docs` folder)~

### CODE REVIEW

File: lib/test/clojure_lsp/features/file_management_test.clj [hunk 1]
```diff
@@ -5,7 +5,9 @@
    [clojure-lsp.shared :as shared]
    [clojure-lsp.test-helper :as h]
    [clojure.test :refer [are deftest is testing]]
-   [medley.core :as medley]))
+   [medley.core :as medley]
+   [clojure-lsp.feature.rename :as f.rename]
+   [clojure-lsp.queries :as q]))
```
Comment (ericdallo) [inline lib/test/clojure_lsp/features/file_management_test.clj:10]: I wonder how lint didn't catch this on `clean-ns` 🤔 maybe it's not running for tests...

File: lib/src/clojure_lsp/feature/file_management.clj [hunk 2]
```diff
@@ -263,6 +263,10 @@
       (shared/dissoc-in [:analysis filename])
       (shared/dissoc-in [:findings filename])))
 
+(defn ^:private file-deleted [db* uri filename]
+  (swap! db* db-without-file uri filename)
+  (f.diagnostic/publish-empty-diagnostics! uri @db*))
```
Comment (ericdallo) [inline lib/src/clojure_lsp/feature/file_management.clj:268]: That's a good pratice, we were really missing that, I noticed some time ago when I would do lots of renames and see old diagnostics

Comment (ericdallo) [reply lib/src/clojure_lsp/feature/file_management.clj:268]: oh, we were just missing for file watch, I see

File: lib/test/clojure_lsp/features/file_management_test.clj (hunk 1 above)
Comment (mainej) [reply lib/test/clojure_lsp/features/file_management_test.clj:10]: Good question... I'll run clean-ns manually, but it'd be nice for the lint CI to catch that.

**Review by ericdallo — APPROVED** [review]
Looks good, tested manually as well

One other approach would be to handle differently if client supports willRenameFiles since it's a pretty recent feature from LSP 3.17, probably only main editos have support for it, but, your approach looks better, we don't need to handle differently checking the capability, it's a little bit more complex though

File: lib/test/clojure_lsp/features/file_management_test.clj (hunk 1 above)
Comment (mainej) [reply lib/test/clojure_lsp/features/file_management_test.clj:10]: Nm... you're too fast!

**Comment by mainej** [comment]
Thanks for doing another test. If you'd like, I can research special behavior for clients that support willRenameFiles, but as you said, it's working so maybe isn't worth more effort. 🤷

**Comment by ericdallo** [comment]
Yeah, it's not necessary, current approach looks good

File: lib/src/clojure_lsp/feature/file_management.clj (hunk 2 above)
Comment (mainej) [reply lib/src/clojure_lsp/feature/file_management.clj:268]: Should we implement [`workspace/didDeleteFiles`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didDeleteFiles)?
