### PR TITLE
Fix create test duplicate deftest

### LINKED ISSUE #2274: `Create test` code action appends a duplicate deftest when one already exists
**Describe the bug**
When invoking the **"Create test for '\<fn\>'"** code action on a function that already has a matching `deftest` in the test namespace, clojure-lsp appends a second identical `(deftest <fn>-test ...)` to the test file instead of navigating to the one that is already there.

**To Reproduce**
1. Open a source file, e.g. `src/my/ns.clj`, with a function:
   ```clojure
   (ns my.ns)

   (defn greet [name]
     (str "Hello, " name))
   ```
2. Place the cursor on `greet` and invoke **"Create test for 'greet'"**. A test file is created at `test/my/ns_test.clj` containing `(deftest greet-test ...)`.
3. Go back to `src/my/ns.clj`, place the cursor on `greet` again, and invoke **"Create test for 'greet'"** a second time.

**Expected behavior**
The editor navigates to the existing `(deftest greet-test ...)` in `test/my/ns_test.clj`. The file is not modified.

### PR DESCRIPTION
**Pull request by jramosg**
- [x] I created an issue to discuss the problem I am trying to solve or an open issue already exists.
- [x] I added a new entry to [CHANGELOG.md](https://github.com/clojure-lsp/clojure-lsp/blob/master/CHANGELOG.md)
- [x] I updated documentation if applicable (`docs` folder)

Fix `create-test` code action appending a duplicate `deftest` when one with the matching name already exists, now navigating to the existing deftest instead.
Fixes #2274

### CODE REVIEW

File: lib/src/clojure_lsp/refactor/transform.clj [hunk 1]
```diff
@@ -1683,6 +1683,22 @@
         (create-function-for-alias local-zloc ns-or-alias defn-loc uri db)
         [(prepend-preserving-comment (edit/to-top local-zloc) defn-loc)]))))
 
+(defn- deftest-loc-with-name
```
Comment (ericdallo) [inline lib/src/clojure_lsp/refactor/transform.clj]:
```suggestion
(defn ^:private deftest-loc-with-name
```

**Review by ericdallo — APPROVED** [review]
Looks good!

**Comment by ericdallo** [comment]
@jramosg can you check lint CI failing? otherwise looks good

**Comment by jramosg** [comment]
> @jramosg can you check lint CI failing? otherwise looks good

done, thanks!!
