### PR TITLE
Skip rename of a namespace if it can be found in multiple files

### LINKED ISSUE #1574: File renames changing src files when renaming a test file
**Describe the bug**
When I rename a `test` file, all the imports on my `src` files are changed

**To Reproduce**
1. Clone or open a [project](https://github.com/ericdallo/clojure-sample)
2. Create a file on the `test` directory that has the same `ns` as any `src` file. (ex: `clojure-sample.lsp.call-hierarchy.a`)
3. Rename the file (SPC + f + R on doom-emacs)
4. All the imports of that `ns` will change on `src` files.

**Expected behavior**
Rename only the `test` files if I change a test file.

**User details (please complete the following information):**
 - OS: Debian 11
 - Editor emacs (doom-emacs)
 - Version: clojure-lsp 2023.01.26-11.08.16 / clj-kondo 2023.01.20

**Additional context**
It is not a critical bug but could lead to some errors if we don't pay attention.

### PR DESCRIPTION
**Pull request by janosmeszaros**
- [x] I created an issue to discuss the problem I am trying to solve or an open issue already exists.
- [x] I added a new entry to [CHANGELOG.md](https://github.com/clojure-lsp/clojure-lsp/blob/master/CHANGELOG.md)

Fixes  #1574

### CODE REVIEW

File: lib/src/clojure_lsp/queries.clj [hunk 1]
```diff
@@ -835,3 +835,11 @@
           (filter #(and (:import %)
                         (safe-equal? class-name (:class %)))))
         (:analysis db)))
+
+(defn find-all-definitions-of-namespace [db namespace]
```
Comment (ericdallo) [inline lib/src/clojure_lsp/queries.clj:839]: since this function searchs only in the project and not whole analysis, can't we name it `find-all-project-namespace-definitions`?

Comment (janosmeszaros) [reply lib/src/clojure_lsp/queries.clj]: That's a better name, for sure.
Renamed the fn and added some more tests.
