### PR TITLE
Fix suggesting alias to wrong lang

### LINKED ISSUE #1024: bug: `add-missing-libspec` will suggest an alias to the wrong language
**Describe the bug**

`add-missing-libspec` will suggest an alias to the wrong language.

```clojure
;; foo/s.cljs
(ns foo.s)
;; a.cljs
(ns a (:require [foo.s :as s]))
;; b.clj
(ns b)
|s/thing
```

This will suggest `(:require [foo.s :as s])` even though `foo.s` isn't a clj namespace.

This is because `find-alias-ns-pairs` and `find-missing-ns-alias-require` should consider file lang but don't. There is a test for this "aliases > Do not add from wrong language" but it can be made to fail if `foo.s` is defined in a cljs file. That is, the tests pass because the namespace isn't defined, not because it's in the wrong language.

### PR DESCRIPTION
**Pull request by mainej**
This prevents `add-missing-libspec` from suggesting an alias to a file in the the wrong language.

```clojure
;; foo/s.cljs
(ns foo.s)
;; a.cljs
(ns a (:require [foo.s :as s]))
;; b.clj
(ns b)
|s/thing
```

This would suggest `(:require [foo.s :as s])` even though `foo.s` isn't a clj namespace.

Fixes #1024

- [x] I created an issue to discuss the problem I am trying to solve or an open issue already exists. #1024
- [X] I added a new entry to [CHANGELOG.md](https://github.com/clojure-lsp/clojure-lsp/blob/master/CHANGELOG.md)
- ~I updated documentation if applicable (`docs` folder)~

### CODE REVIEW

File: lib/test/clojure_lsp/feature/add_missing_libspec_test.clj [hunk 1]
```diff
@@ -211,6 +211,7 @@
     (testing "Do not add from wrong language"
```
Comment (mainej) [inline lib/test/clojure_lsp/feature/add_missing_libspec_test.clj:211]: This test was passing not because of the mismatch between languages as its name suggests, but because `foo.s` wasn't defined and because undefined namespaces aren't suggested. Adding the definition of `foo.s` in a cljs file made it fail and the rest of this patch is the fix.

File: lib/src/clojure_lsp/queries.clj [hunk 2]
```diff
@@ -510,34 +510,42 @@
                      (= (:name-end-col %) (:name-end-col keyword-element))))
        first))
 
-(defn find-all-ns-definition-names-xf []
+(def find-all-ns-definitions-xf
```
Comment (ericdallo) [inline lib/src/clojure_lsp/queries.clj:513]: 👍🏻

**Review by ericdallo — APPROVED** [review]
