### PR TITLE
Fix drag destructured keys

### LINKED ISSUE #927: move-coll-entry moves :keys destructuring in pairs
**Describe the bug**
move-coll-entry moves :keys destructuring in pairs

**To Reproduce**
Happens in fn parameters and let bindings. Also explains why with uneven keys, nothing happens.

```clojure
(let [{:keys [a b |c d]} x] 1)
;;=expected>
(let [{:keys [a |c b d]} x] 1)
;;=actual>
(let [{:keys [c d |a b]} x] 1)
```

```clojure
(let [{:keys [a |b c]} x] 1)
;;=expected>
(let [{:keys [|b a c]} x] 1)
;;=actual>
(let [{:keys [a |b c]} x] 1)
```

clojure-lsp 2022.02.23-12.12.12
clj-kondo 2022.02.09

### PR DESCRIPTION
**Pull request by mainej**
Drag element-wise, not pair-wise. Fixes #927.

- [x] I created a issue to discuss the problem I am trying to solve or there is already a open issue.
- [x] I added a new entry to [CHANGELOG.md](https://github.com/clojure-lsp/clojure-lsp/blob/master/CHANGELOG.md)

### CODE REVIEW

File: lib/src/clojure_lsp/feature/drag.clj [hunk 1]
```diff
@@ -366,27 +366,38 @@
...
+                             {:name-row     (:row nmeta)
+                              :name-col     (:col nmeta)
+                              :name-end-row (:end-row nmeta)
+                              :name-end-col (:end-col nmeta)}))]
+          (when (even? (count child-nodes))
+            (let [analysis (filter #(shared/inside? % (node-scope (z/node vector-zloc)))
+                                   (get analysis (shared/uri->filename uri)))]
+              (->> child-nodes
+                   (partition 2)
+                   (every? (fn [[lvar rvar]]
```
Comment (ericdallo) [inline lib/src/clojure_lsp/feature/drag.clj:393]: Sometimes I forgot how partition could be so handful

**Review by ericdallo — APPROVED** [review]

**Comment by ericdallo** [comment]
Looks good, just need to fix lint

File: lib/src/clojure_lsp/feature/drag.clj (hunk 1 above)
Comment (mainej) [reply lib/src/clojure_lsp/feature/drag.clj:393]: 👍 it's a useful tool. I recently re-discovered `list*`, which is useful for constructing s-expressions.
